stages:
  prepare:
    cmd: python src/chocolate_features.py
    deps:
      - data/flavors_of_cacao.csv
      - src/chocolate_features.py
    outs:
      - data/chocolate_pipeline.pkl
      - data/chocolate_processed_train.csv
      - data/chocolate_processed_test.csv
    params:
      - features.target
      - features.data